### ISSUE TITLE
Did @serkankaya get an avatar?

### ISSUE THREAD

**Issue by mrvavilon** [kitschbent/hopr-leaderboard#3]

**Comment by kitschbent** [comment]
[https://app.zenhub.com/files/309549730/52cc996a-d7d6-44f9-b172-5c0d18ee23f1/download](https://app.zenhub.com/files/309549730/52cc996a-d7d6-44f9-b172-5c0d18ee23f1/download)

**Comment by kitschbent** [comment]
let's see if this works
