### ISSUE TITLE
Task№12 - 16Uiu2HAkxxiYUagSbiKdX4Ekz2BRs1dyBqGRVPGrDf2tswzKrPkN

### ISSUE THREAD

**Issue by mrvavilon** [kitschbent/hopr-leaderboard#4]
Please check the user's answer in task №12. A user posted a question via the node on November 22 at approximately 6 PM UTC. According to the screenshot, the message was sent successfully. But the user is not listed on the github.
![photo_2020-11-24_23-58-45.jpg](https://images.zenhubusercontent.com/5fbd59415f94b99853a93f1b/cf03133c-a0e9-45d7-9bd9-7218cd409ef3)16Uiu2HAkxxiYUagSbiKdX4Ekz2BRs1dyBqGRVPGrDf2tswzKrPkN

**Comment by kitschbent** [comment]
No address match in the raw logs from node for this day.

I searched for the message itself (the task for day 12).  There is no hit for the word `roughly` and the closest for `developers` is this entry, from a different address:

```
===== New message ======
Message: 16Uiu2HAkzz6ciBeuPCJ4mL3BCgbPhW4SyRwn8jd4gv8Q8w3P2Q5W:How many developers you have?
Latency: 1312 ms
========================

```

I see they are running in tmux. Also, server name `hopr2` implies there is a `hopr1` so perhaps they are running on the same IP addr or some other known issue

**Comment by mrvavilon** [comment]
Thank you!
