### ISSUE TITLE
Task №9 - 16Uiu2HAmNpeae5rFFpDfNpU1YwUNci3NHmBWM1zdEhYZ3E19BUiE

### ISSUE THREAD

**Issue by mrvavilon** [kitschbent/hopr-leaderboard#5]
Check the user's answer in task№9. User uploaded a screenshot. Based on the screenshot, the message was sent successfully. But the user is not listed.

![image.png](https://images.zenhubusercontent.com/5fbd59415f94b99853a93f1b/01cb6d81-c70b-42db-9b0d-680c6062589f)

**Comment by kitschbent** [comment]
The address doesn't appear in the raw logs. Meaning, it didn't come in to the node. Going forward we plan to automate a response to assure the Tx went through entirely. The screenshots are not definitive in that the success prompt you'd normally see is used with a following command. But, the goal is to automate this going forward.
